export const project1Styles = {
  page: {
    backgroundColor: "#ffffff",
    minHeight: "100vh",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    color: "#1a1a1a",
    lineHeight: 1.7,
  } as React.CSSProperties,
  container: {
    maxWidth: "900px",
    margin: "0 auto",
    padding: "80px 24px",
  } as React.CSSProperties,
  tags: {
    fontSize: "13px",
    color: "#888888",
    letterSpacing: "0.5px",
    marginBottom: "24px",
    fontWeight: 400,
  } as React.CSSProperties,
  title: {
    fontSize: "clamp(42px, 6vw, 64px)",
    fontWeight: 700,
    marginBottom: "24px",
    letterSpacing: "-1.5px",
    lineHeight: 1.1,
  } as React.CSSProperties,
  subtitle: {
    fontSize: "20px",
    color: "#444444",
    fontWeight: 400,
    lineHeight: 1.6,
    marginBottom: "100px",
  } as React.CSSProperties,
  section: {
    marginBottom: "100px",
  } as React.CSSProperties,
  sectionHeading: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#888888",
    textTransform: "uppercase" as const,
    letterSpacing: "1.5px",
    marginBottom: "24px",
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: "32px",
    fontWeight: 600,
    marginBottom: "24px",
    letterSpacing: "-0.5px",
    fontFamily: "'Instrument Serif', serif",
    fontStyle: "italic",
  } as React.CSSProperties,
  paragraph: {
    fontSize: "17px",
    color: "#333333",
    lineHeight: 1.8,
    marginBottom: "20px",
  } as React.CSSProperties,
  carouselWrapper: {
    position: "relative" as const,
    marginBottom: "60px",
    marginLeft: "-24px",
    marginRight: "-24px",
    width: "calc(100% + 48px)",
  } as React.CSSProperties,
  carouselFadeLeft: {
    position: "absolute" as const,
    left: 0,
    top: 0,
    bottom: 0,
    width: "80px",
    background: "linear-gradient(to right, rgba(255,255,255,1) 0%, rgba(255,255,255,0) 100%)",
    pointerEvents: "none" as const,
    zIndex: 5,
  } as React.CSSProperties,
  carouselFadeRight: {
    position: "absolute" as const,
    right: 0,
    top: 0,
    bottom: 0,
    width: "80px",
    background: "linear-gradient(to left, rgba(255,255,255,1) 0%, rgba(255,255,255,0) 100%)",
    pointerEvents: "none" as const,
    zIndex: 5,
  } as React.CSSProperties,
  carouselContainer: {
    display: "flex",
    gap: "40px",
    overflowX: "auto" as const,
    scrollBehavior: "smooth" as const,
    paddingTop: "40px",
    paddingBottom: "40px",
    paddingLeft: "max(24px, calc(50% - 240px))",
    paddingRight: "max(24px, calc(50% - 240px))",
    scrollbarWidth: "none" as const,
    msOverflowStyle: "none" as const,
  } as React.CSSProperties,
  carouselImage: (isHovered: boolean): React.CSSProperties => ({
    minWidth: "480px",
    height: "320px",
    backgroundColor: "#f5f5f5",
    borderRadius: "0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#999999",
    fontSize: "15px",
    fontWeight: 500,
    boxShadow: isHovered
      ? "0 20px 40px rgba(0,0,0,0.12)"
      : "0 4px 20px rgba(0,0,0,0.06)",
    transition: "all 0.3s ease",
    transform: isHovered ? "translateY(-8px)" : "translateY(0)",
    cursor: "pointer",
    flexShrink: 0,
  }),
  carouselButton: {
    position: "absolute" as const,
    top: "50%",
    transform: "translateY(-50%)",
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    backgroundColor: "#ffffff",
    border: "1px solid #eeeeee",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
    color: "#333333",
    boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
    transition: "all 0.2s ease",
    zIndex: 10,
  } as React.CSSProperties,
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "40px",
    marginBottom: "100px",
    paddingTop: "40px",
    borderTop: "1px solid #f0f0f0",
  } as React.CSSProperties,
  detailItem: {
    textAlign: "left" as const,
  } as React.CSSProperties,
  detailLabel: {
    fontSize: "12px",
    color: "#888888",
    textTransform: "uppercase" as const,
    letterSpacing: "1.5px",
    marginBottom: "8px",
    fontWeight: 500,
  } as React.CSSProperties,
  detailValue: {
    fontSize: "16px",
    color: "#1a1a1a",
    fontWeight: 500,
  } as React.CSSProperties,
  quote: {
    fontSize: "28px",
    fontStyle: "italic",
    textAlign: "center" as const,
    color: "#333333",
    lineHeight: 1.5,
    padding: "60px 40px",
    marginBottom: "100px",
    borderLeft: "none",
    fontWeight: 400,
    letterSpacing: "-0.3px",
  } as React.CSSProperties,
  imagePlaceholder: (isHovered: boolean): React.CSSProperties => ({
    width: "100%",
    height: "400px",
    backgroundColor: "#f8f8f8",
    borderRadius: "0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#aaaaaa",
    fontSize: "15px",
    fontWeight: 500,
    marginTop: "32px",
    marginBottom: "16px",
    boxShadow: isHovered
      ? "0 20px 40px rgba(0,0,0,0.08)"
      : "0 2px 8px rgba(0,0,0,0.04)",
    transition: "all 0.3s ease",
    transform: isHovered ? "scale(1.01)" : "scale(1)",
    cursor: "pointer",
  }),
  bulletList: {
    listStyle: "none",
    padding: 0,
    margin: "24px 0",
  } as React.CSSProperties,
  bulletItem: {
    fontSize: "17px",
    color: "#333333",
    lineHeight: 1.8,
    paddingLeft: "24px",
    position: "relative" as const,
    marginBottom: "12px",
  } as React.CSSProperties,
  bulletDot: {
    position: "absolute" as const,
    left: 0,
    top: "12px",
    width: "6px",
    height: "6px",
    backgroundColor: "#cccccc",
    borderRadius: "50%",
  } as React.CSSProperties,
  impactGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "60px",
    marginTop: "32px",
  } as React.CSSProperties,
  impactCard: {
    padding: "0",
  } as React.CSSProperties,
  impactTitle: {
    fontSize: "18px",
    fontWeight: 600,
    marginBottom: "12px",
    color: "#1a1a1a",
  } as React.CSSProperties,
  impactText: {
    fontSize: "16px",
    color: "#555555",
    lineHeight: 1.7,
  } as React.CSSProperties,
  divider: {
    height: "1px",
    backgroundColor: "#f0f0f0",
    margin: "80px 0",
  } as React.CSSProperties,
};
